version: '3.4'

networks:
  openai:
    external: true

services:
  openairestapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AZURE_CLIENT_ID=5b7698bf-19cd-4ef9-857c-ea1b74f9b556
      - AZURE_TENANT_ID=72f988bf-86f1-41af-91ab-2d7cd011db47
      - AZURE_CLIENT_SECRET=IHD8Q~bCRU~hWliUacT-CFnS.2nsdwNKzUlmJbtp
    ports:
      - "8000:80"
      - "8001:443"
      - "8002:6000"  
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - openai

  prometheus:
    build: 
      context: ./scripts/prometheus
    depends_on:
      - openairestapi
    ports:
      - 9090:9090
    networks:
      - openai

  grafana:
    build: 
      context: ./scripts/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - openai